namespace LewdFilter.Domain.Constants;

public static class AugmentBaseTypeConstants
{
    public static readonly IReadOnlyList<string> AugmentAldur =
    [
        "Ancient Rune of Animosity",
        "Ancient Rune of Control",
        "Ancient Rune of Decay",
        "Ancient Rune of Detonation",
        "Ancient Rune of Discovery",
        "Ancient Rune of Dueling",
        "Ancient Rune of Prowess",
        "Ancient Rune of Retaliation",
        "Ancient Rune of Shattering",
        "Ancient Rune of Splinters",
        "Ancient Rune of the Horde",
        "Ancient Rune of the Titan",
        "Ancient Rune of Witchcraft",
        "Rune of Accumulation",
        "Rune of Acrobatics",
        "Rune of Confrontation",
        "Rune of Consistency",
        "Rune of Culmination",
        "Rune of Foundations",
        "Rune of Reach",
        "Rune of Renown",
        "Rune of the Blossom",
        "Rune of the Hunt",
        "Rune of the Prism",
        "Rune of Vital Flame",
        "Rune of Vitality",
        "Warding Rune of Annihilation",
        "Warding Rune of Armature",
        "Warding Rune of Bodyguards",
        "Warding Rune of Courage",
        "Warding Rune of Desperation",
        "Warding Rune of Disintegration",
        "Warding Rune of Equinox",
        "Warding Rune of Glancing",
        "Warding Rune of Heart",
        "Warding Rune of Hollowing",
        "Warding Rune of Nourishment",
        "Warding Rune of Obsession",
        "Warding Rune of Protection",
        "Warding Rune of Reinforcement",
        "Warding Rune of Salvaging",
        "Warding Rune of Stability",
        "Warding Rune of Symbiosis",
    ];

    public static readonly IReadOnlyList<string> AugmentAncient =
    [
        "Amanamu's Gaze",
        "Emergent Instinct",
        "Emergent Possibility",
        "Emergent Protection",
        "Emergent Vigour",
        "Kurgal's Gaze",
        "Tecrod's Gaze",
        "Ulaman's Gaze",
    ];

    public static readonly string[] AugmentBase =
    [
        "Greater Body Rune",
        "Greater Charging Rune",
        "Greater Desert Rune",
        "Greater Glacial Rune",
        "Greater Inspiration Rune",
        "Greater Iron Rune",
        "Greater Mind Rune",
        "Greater Rebirth Rune",
        "Greater Resolve Rune",
        "Greater Storm Rune",
        "Greater Stone Rune",
        "Greater Vision Rune",
        "Greater Ward Rune",
        "Body Rune",
        "Charging Rune",
        "Desert Rune",
        "Glacial Rune",
        "Inspiration Rune",
        "Iron Rune",
        "Mind Rune",
        "Rebirth Rune",
        "Resolve Rune",
        "Storm Rune",
        "Stone Rune",
        "Vision Rune",
        "Ward Rune",
        "Lesser Body Rune",
        "Lesser Charging Rune",
        "Lesser Desert Rune",
        "Lesser Glacial Rune",
        "Lesser Inspiration Rune",
        "Lesser Iron Rune",
        "Lesser Mind Rune",
        "Lesser Rebirth Rune",
        "Lesser Resolve Rune",
        "Lesser Storm Rune",
        "Lesser Stone Rune",
        "Lesser Vision Rune",
        "Lesser Ward Rune",
    ];

    public static readonly string[] AugmentIdol =
    [
        "Bear Idol",
        "Boar Idol",
        "Carved Cunning",
        "Carved Majesty",
        "Carved Mischief",
        "Carved Tenacity",
        "Cat Idol",
        "Fox Idol",
        "Hawk Idol",
        "Idol of Alira",
        "Idol of Eeshta",
        "Idol of Egrin",
        "Idol of Eramir",
        "Idol of Greust",
        "Idol of Grold",
        "Idol of Kraityn",
        "Idol of Maxarius",
        "Idol of Oak",
        "Idol of Ralakesh",
        "Idol of Silk",
        "Idol of Sirrius",
        "Idol of the Martyr",
        "Idol of the Pharisee",
        "Idol of the Sycophant",
        "Idol of Thruldana",
        "Idol of Yeena",
        "Owl Idol",
        "Ox Idol",
        "Panther Idol",
        "Primate Idol",
        "Rabbit Idol",
        "Snake Idol",
        "Stag Idol",
        "Stoat Idol",
        "Wolf Idol",
    ];

    public static readonly IReadOnlyList<string> AugmentSoulCore =
    [
        "Atmohua's Soul Core of Retreat",
        "Cholotl's Soul Core of War",
        "Citaqualotl's Soul Core of Foulness",
        "Citaqualotl's Thesis",
        "Estazunti's Soul Core of Convalescence",
        "Guatelitzi's Soul Core of Endurance",
        "Guatelitzi's Thesis",
        "Hayoxi's Soul Core of Heatproofing",
        "Jiquani's Thesis",
        "Opiloti's Soul Core of Assault",
        "Quipolatl's Soul Core of Flow",
        "Quipolatl's Thesis",
        "Soul Core of Atmohua",
        "Soul Core of Azcapa",
        "Soul Core of Cholotl",
        "Soul Core of Citaqualotl",
        "Soul Core of Jiquani",
        "Soul Core of Opiloti",
        "Soul Core of Puhuarte",
        "Soul Core of Quipolatl",
        "Soul Core of Tacati",
        "Soul Core of Ticaba",
        "Soul Core of Topotante",
        "Soul Core of Tzamoto",
        "Soul Core of Xopec",
        "Soul Core of Zalatl",
        "Soul Core of Zantipi",
        "Tacati's Soul Core of Affliction",
        "Topotante's Soul Core of Dampening",
        "Tzamoto's Soul Core of Ferocity",
        "Uromoti's Soul Core of Attenuation",
        "Xipocado's Soul Core of Dominion",
        "Xopec's Soul Core of Power",
        "Zalatl's Soul Core of Insulation",
    ];

    public static readonly IReadOnlyList<string> AugmentUnique =
    [
        "Aldur's Legacy",
        "Astrid's Creativity",
        "Betrayal of Aldur",
        "Breath of Aldur",
        "Cadigan's Epiphany",
        "Countess Seske's Rune of Archery",
        "Courtesan Mannan's Rune of Cruelty",
        "Craiceann's Rune of Recovery",
        "Craiceann's Rune of Warding",
        "Farrul's Rune of Grace",
        "Farrul's Rune of the Chase",
        "Farrul's Rune of the Hunt",
        "Fenumus' Rune of Agony",
        "Fenumus' Rune of Draining",
        "Fenumus' Rune of Spinning",
        "Hedgewitch Assandra's Rune of Wisdom",
        "Ire of Aldur",
        "Katla's Gloom",
        "Kolr's Hunt",
        "Lady Hestra's Rune of Winter",
        "Medved's Tending",
        "Passion of Aldur",
        "Saqawal's Rune of Erosion",
        "Saqawal's Rune of Memory",
        "Saqawal's Rune of the Sky",
        "Serle's Triumph",
        "Thane Girt's Rune of Wildness",
        "Thane Grannell's Rune of Mastery",
        "Thane Leld's Rune of Spring",
        "Thane Myrk's Rune of Summer",
        "The Greatwolf's Rune of Claws",
        "The Greatwolf's Rune of Willpower",
        "Thrud's Might",
        "Uhtred's Sidereus",
        "Vorana's Carnage",
    ];
}
