namespace LewdFilter.Domain.Constants;

public class CurrencyBaseTypeConstants
{
    public static readonly IReadOnlyList<string> CurrencyBase =
    [
        "Arcanist's Etcher",
        "Architect's Orb",
        "Armourer's Scrap",
        "Artificer's Orb",
        "Artificer's Shard",
        "Blacksmith's Whetstone",
        "Blazing Flux",
        "Chaos Orb",
        "Chilling Flux",
        "Core Destabiliser",
        "Crackling Flux",
        "Cryptic Key",
        "Crystallised Corruption",
        "Divine Orb",
        "Exalted Orb",
        "Exceptional Verisium",
        "Fracturing Orb",
        "Gemcutter's Prism",
        "Glassblower's Bauble",
        "Greater Jeweller's Orb",
        "Hinekora's Lock",
        "Lesser Jeweller's Orb",
        "Medved's Crest of the Circle",
        "Mirror of Kalandra",
        "Olroth's Crest of the Sun",
        "Orb of Alchemy",
        "Orb of Annulment",
        "Orb of Augmentation",
        "Orb of Chance",
        "Orb of Extraction",
        "Orb of Transmutation",
        "Perfect Flux",
        "Perfect Jeweller's Orb",
        "Regal Orb",
        "Regal Shard",
        "Scroll of Wisdom",
        "Transmutation Shard",
        "Uhtred's Crest of the Chalice",
        "Vaal Arcanist's Infuser",
        "Vaal Armourer's Infuser",
        "Vaal Blacksmith's Infuser",
        "Vaal Catalysing Infuser",
        "Vaal Cultivation Orb",
        "Vaal Infuser",
        "Vaal Orb",
        "Vaal Siphoner",
        "Verisium",
        "Void Flux",
        "Vorana's Crest of the Scythe",
    ];

    public static readonly IReadOnlyList<string> CurrencyAbyssal =
    [
        "Altered Collarbone",
        "Ancient Collarbone",
        "Ancient Infuser",
        "Ancient Jawbone",
        "Ancient Rib",
        "Gnawed Collarbone",
        "Gnawed Jawbone",
        "Gnawed Rib",
        "Preserved Collarbone",
        "Preserved Cranium",
        "Preserved Jawbone",
        "Preserved Rib",
        "Preserved Vertebrae",
    ];

    public static readonly IReadOnlyList<string> CurrencyAldur =
    [
        "Blazing Flux",
        "Chilling Flux",
        "Crackling Flux",
        "Exceptional Verisium",
        "Medved's Crest of the Circle",
        "Olroth's Crest of the Sun",
        "Perfect Flux",
        "Starlit Ore",
        "Revered Starlit Ore",
        "Sovereign Starlit Ore",
        "Transcendent Starlit Ore",
        "Veridical Starlit Ore",
        "Warding Starlit Ore",
        "Uhtred's Crest of the Chalice",
        "Verisium",
        "Vorana's Crest of the Scythe",
    ];


    public static readonly IReadOnlyList<string> Alloys =
    [
        "Adaptive Alloy",
        "Celestial Alloy",
        "Cyclonic Alloy",
        "Expansive Alloy",
        "Mystic Alloy",
        "Prismatic Alloy",
        "Protective Alloy",
        "Runic Alloy",
        "Sovereign Alloy",
        "Swift Alloy",
        "The Runebinder's Alloy",
        "The Runefather's Alloy",
        "Transcendent Alloy",
    ];

    public static readonly IReadOnlyList<string> OmenBase =
    [
        "Omen of Amelioration",
        "Omen of Answered Prayers",
        "Omen of Bartering",
        "Omen of Catalysing Exaltation",
        "Omen of Chance",
        "Omen of Chaotic Monsters",
        "Omen of Chaotic Quantity",
        "Omen of Chaotic Rarity",
        "Omen of Corruption",
        "Omen of Dextral Alchemy",
        "Omen of Dextral Annulment",
        "Omen of Dextral Coronation",
        "Omen of Dextral Crystallisation",
        "Omen of Dextral Erasure",
        "Omen of Dextral Exaltation",
        "Omen of Gambling",
        "Omen of Greater Annulment",
        "Omen of Greater Exaltation",
        "Omen of Homogenising Coronation",
        "Omen of Homogenising Exaltation",
        "Omen of Recombination",
        "Omen of Refreshment",
        "Omen of Reinforcements",
        "Omen of Resurgence",
        "Omen of Sanctification",
        "Omen of Secret Compartments",
        "Omen of Sinistral Alchemy",
        "Omen of Sinistral Annulment",
        "Omen of Sinistral Coronation",
        "Omen of Sinistral Crystallisation",
        "Omen of Sinistral Erasure",
        "Omen of Sinistral Exaltation",
        "Omen of the Ancients",
        "Omen of the Blessed",
        "Omen of the Hunt",
        "Omen of Whittling",
    ];

    public static readonly IReadOnlyList<string> OmenAbyssal =
    [
        "Omen of Abyssal Echoes",
        "Omen of Light",
        "Omen of Putrefaction",
        "Omen of Dextral Necromancy",
        "Omen of Sinistral Necromancy",
        "Omen of the Blackblooded",
        "Omen of the Liege",
        "Omen of the Sovereign",
    ];

    public static readonly string[] Essence =
    [
        "Essence of Battle",
        "Essence of Delirium",
        "Essence of Electricity",
        "Essence of Enhancement",
        "Essence of Flames",
        "Essence of Haste",
        "Essence of Horror",
        "Essence of Hysteria",
        "Essence of Ice",
        "Essence of Insanity",
        "Essence of Ruin",
        "Essence of Sorcery",
        "Essence of the Abyss",
        "Essence of the Body",
        "Essence of the Infinite",
        "Essence of the Mind",
        "Essence of Torment",
        "Greater Essence of Battle",
        "Greater Essence of Electricity",
        "Greater Essence of Enhancement",
        "Greater Essence of Flames",
        "Greater Essence of Haste",
        "Greater Essence of Ice",
        "Greater Essence of Ruin",
        "Greater Essence of Sorcery",
        "Greater Essence of the Body",
        "Greater Essence of the Infinite",
        "Greater Essence of the Mind",
        "Greater Essence of Torment",
        "Lesser Essence of Battle",
        "Lesser Essence of Electricity",
        "Lesser Essence of Enhancement",
        "Lesser Essence of Flames",
        "Lesser Essence of Haste",
        "Lesser Essence of Ice",
        "Lesser Essence of Ruin",
        "Lesser Essence of Sorcery",
        "Lesser Essence of the Body",
        "Lesser Essence of the Infinite",
        "Lesser Essence of the Mind",
        "Lesser Essence of Torment",
        "Perfect Essence of Battle",
        "Perfect Essence of Electricity",
        "Perfect Essence of Enhancement",
        "Perfect Essence of Flames",
        "Perfect Essence of Haste",
        "Perfect Essence of Ice",
        "Perfect Essence of Ruin",
        "Perfect Essence of Sorcery",
        "Perfect Essence of the Body",
        "Perfect Essence of the Infinite",
        "Perfect Essence of the Mind",
        "Perfect Essence of Torment",
    ];

    public static readonly string[] EssenceUnique =
    [
        "Essence of the Abyss",
        "Essence of Hysteria",
        "Essence of Horror",
        "Essence of Insanity",
        "Essence of Delirium",
    ];

    public static readonly string[] Catalyst =
    [
        "Adaptive Catalyst",
        "Carapace Catalyst",
        "Chayula's Catalyst",
        "Esh's Catalyst",
        "Flesh Catalyst",
        "Neural Catalyst",
        "Reaver Catalyst",
        "Sibilant Catalyst",
        "Skittering Catalyst",
        "Tul's Catalyst",
        "Uul-Netol's Catalyst",
        "Xoph's Catalyst",
    ];

    public static readonly string[] CatalystRefined =
    [
        "Refined Adaptive Catalyst",
        "Refined Carapace Catalyst",
        "Refined Chayula's Catalyst",
        "Refined Esh's Catalyst",
        "Refined Flesh Catalyst",
        "Refined Neural Catalyst",
        "Refined Reaver Catalyst",
        "Refined Sibilant Catalyst",
        "Refined Skittering Catalyst",
        "Refined Tul's Catalyst",
        "Refined Uul-Netol's Catalyst",
        "Refined Xoph's Catalyst",
    ];

    public static readonly string[] LiquidEmotion =
    [
        "Ancient Concentrated Liquid Fear",
        "Ancient Concentrated Liquid Isolation",
        "Ancient Concentrated Liquid Suffering",
        "Ancient Diluted Liquid Greed",
        "Ancient Diluted Liquid Guilt",
        "Ancient Diluted Liquid Ire",
        "Ancient Liquid Despair",
        "Ancient Liquid Disgust",
        "Ancient Liquid Envy",
        "Ancient Liquid Paranoia",
        "Ancient Potent Liquid Contempt",
        "Ancient Potent Liquid Ferocity",
        "Ancient Potent Liquid Melancholy",
        "Concentrated Liquid Fear",
        "Concentrated Liquid Isolation",
        "Concentrated Liquid Suffering",
        "Diluted Liquid Greed",
        "Diluted Liquid Guilt",
        "Diluted Liquid Ire",
        "Liquid Despair",
        "Liquid Disgust",
        "Liquid Envy",
        "Liquid Paranoia",
    ];
}
