namespace LewdFilter.Generator;

public class EquipmentConstants
{
    public static string[] EquipmentArmor =
    [
        // Helmet
        "Rusted Greathelm",
        "Soldier Greathelm",
        "Wrapped Greathelm",
        "Spired Greathelm",
        "Elite Greathelm",
        "Warrior Greathelm",
        "Commander Greathelm",
        "Fierce Greathelm",
        "Elegant Greathelm",
        "Noble Greathelm",
        "Warmonger Greathelm",
        "Masked Greathelm",
        "Paragon Greathelm",
        "Imperial Greathelm",
        
        // Chest
        "Rusted Cuirass",
        "Fur Plate",
        "Iron Cuirass",
        "Raider Plate",
        "Maraketh Cuirass",
        "Steel Plate",
        "Full Plate",
        "Vaal Cuirass",
        "Juggernaut Plate",
        "Chieftain Cuirass",
        "Elegant Plate",
        "Stone Cuirass",
        "Soldier Cuirass",
        "Ornate Plate",
        "Utzaal Cuirass",
        "Warlord Cuirass",
        
        "Heavy Plate",
        
        // Gloves
        "Stocky Mitts",
        "Riveted Mitts",
        "Tempered Mitts",
        "Bolstered Mitts",
        "Moulded Mitts",
        "Detailed Mitts",
        "Ancient Mitts",
        "Feathered Mitts",
        "Knightly Mitts",
        "Ornate Mitts",
        "Vaal Mitts",
        "Massive Mitts",
        
        // Boots
        "Rough Greaves",
        "Iron Greaves",
        "Bronze Greaves",
        "Trimmed Greaves",
        "Stone Greaves",
        "Reefsteel Greaves",
        "Elegant Greaves",
        "Carved Greaves",
        "Bulwark Greaves",
        "Ornate Greaves",
        "Vaal Greaves",
        "Tasalian Greaves",
        
        // Shield
        "Splintered Tower Shield",
        "Painted Tower Shield",
        "Braced Tower Shield",
        "Barricade Tower Shield",
        "Effigial Tower Shield",
        "Rampart Tower Shield",
        "Heraldric Tower Shield",
        "Stone Tower Shield",
        "Crucible Tower Shield",
        "Ancestor Tower Shield",
        "Bulwark Tower Shield",
        "Noble Tower Shield",
        "Goldworked Tower Shield",
        "Fortress Tower Shield",
        "Vaal Tower Shield",
        "Tawhoan Tower Shield",
        
        "Royal Tower Shield",
    ];
    
    public static string[] EquipmentEvasion =
    [
        // Helmet
        "Shabby Hood",
        "Felt Cap",
        "Lace Hood",
        "Swathed Cap",
        "Hunter Hood",
        "Viper Cap",
        "Corsair Cap",
        "Leatherbound Hood",
        "Wrapped Cap",
        "Deerstalker Hood",
        "Woven Cap",
        "Desert Cap",
        "Trapper Hood",
        "Freebooter Cap",

        // Chest
        "Leather Vest",
        "Quilted Vest",
        "Pathfinder Coat",
        "Shrouded Vest",
        "Rhoahide Coat",
        "Studded Vest",
        "Scout's Vest",
        "Serpentscale Coat",
        "Corsair Vest",
        "Smuggler Coat",
        "Layered Vest",
        "Runner Vest",
        "Lizardscale Coat",
        "Swiftstalker Coat",
        "Slipstrike Vest",
        "Wyrmscale Coat",
        "Corsair Coat",
        
        // Gloves
        "Suede Bracers",
        "Firm Bracers",
        "Bound Bracers",
        "Sectioned Bracers",
        "Spined Bracers",
        "Fine Bracers",
        "Refined Bracers",
        "Spiked Bracers",
        "Stalking Bracers",
        "Grand Bracers",
        "Barbed Bracers",
        "Polished Bracers",
        
        // Boots
        "Rawhide Boots",
        "Laced Boots",
        "Embossed Boots",
        "Steeltoe Boots",
        "Lizardscale Boots",
        "Flared Boots",
        "Studded Boots",
        "Serpentscale Boots",
        "Cinched Boots",
        "Cavalry Boots",
        "Dragonscale Boots",
        "Drakeskin Boots",
        
        // Shield
        "Leather Buckler",
        "Wooden Buckler",
        "Plated Buckler",
        "Iron Buckler",
        "Ridged Buckler",
        "Spiked Buckler",
        "Ringed Buckler",
        "Edged Buckler",
        "Laminate Buckler",
        "Pearl Buckler",
        "Spikeward Buckler",
        "Jingling Buckler",
        "Bladeguard Buckler",
        "Ornate Buckler",
        "Gutspike Buckler",
        "Ancient Buckler",
        "Desert Buckler",
    ];
    
    public static string[] EquipmentEnergyShield =
    [
        // Helmet
        "Twig Circlet",
        "Wicker Tiara",
        "Beaded Circlet",
        "Chain Tiara",
        "Feathered Tiara",
        "Gold Circlet",
        "Vermeil Circlet",
        "Jade Tiara",
        "Sandsworn Tiara",
        "Jungle Tiara",
        "Skycrown Tiara",
        "Sorcerous Tiara",
        "Kamasan Tiara",
        "Ancestral Tiara",
        
        // Chest
        "Tattered Robe",
        "Feathered Robe",
        "Hexer's Robe",
        "Bone Raiment",
        "Silk Robe",
        "Keth Raiment",
        "Votive Raiment",
        "Altar Robe",
        "Elementalist Robe",
        "Mystic Raiment",
        "River Raiment",
        "Adherent's Raiment",
        "Ceremonial Robe",
        "Vile Robe",
        "Flowing Raiment",
        "Sacramental Robe",
        "Feathered Raiment",
        
        // Gloves
        "Torn Gloves",
        "Sombre Gloves",
        "Stitched Gloves",
        "Jewelled Gloves",
        "Intricate Gloves",
        "Pauascale Gloves",
        "Baroque Gloves",
        "Gold Gloves",
        "Grim Gloves",
        "Opulent Gloves",
        "Vaal Gloves",
        "Sirenscale Gloves",
        
        // Boots
        "Straw Sandals",
        "Wrapped Sandals",
        "Lattice Sandals",
        "Silk Slippers",
        "Feathered Sandals",
        "Flax Sandals",
        "Elegant Slippers",
        "Dunerunner Sandals",
        "Bound Sandals",
        "Luxurious Slippers",
        "Sekhema Sandals",
        
        "Sandsworn Sandals",
        
        // Shield
        "Twig Focus",
        "Woven Focus",
        "Antler Focus",
        "Engraved Focus",
        "Tonal Focus",
        "Crystal Focus",
        "Voodoo Focus",
        "Plumed Focus",
        "Runed Focus",
        "Whorl Focus",
        "Arrayed Focus",
        "Cultist Focus",
        "Hallowed Focus",
        "Druidic Focus",
        "Leyline Focus",
        "Sacred Focus",
        "Tasalian Focus",
    ];
    
    public static string[] EquipmentArmorEvasion =
    [
        // Helmet
        "Brimmed Helm",
        "Guarded Helm",
        "Visored Helm",
        "Cowled Helm",
        "Shielded Helm",
        "Closed Helm",
        "Cabalist Helm",
        "Gladiatoral Helm",
        "Warded Helm",
        "Cryptic Helm",
        "Champion Helm",
        "Gladiatorial Helm",
        
        // Chest
        "Chain Mail",
        "Rogue Armour",
        "Vagabond Armour",
        "Cloaked Mail",
        "Explorer Armour",
        "Scale Mail",
        "Knight Armour",
        "Ancestral Mail",
        "Mantled Mail",
        "Trailblazer Armour",
        "Golden Mail",
        "Dastard Armour",
        "Shrouded Mail",
        "Death Mail",
        "Thane Mail",
                
        // Gloves
        "Ringmail Gauntlets",
        "Layered Gauntlets",
        "Doubled Gauntlets",
        "Plate Gauntlets",
        "Zealot Gauntlets",
        "Steelmail Gauntlets",
        "Commander Gauntlets",
        "Cultist Gauntlets",
        "Blacksteel Gauntlets",
        
        // Boots
        "Mail Sabatons",
        "Braced Sabatons",
        "Stacked Sabatons",
        "Covered Sabatons",
        "Bastion Sabatons",
        "Veteran Sabatons",
        "Noble Sabatons",
        "Fortress Sabatons",
        "Blacksteel Sabatons",
        
        // Shield
        "Hardwood Targe",
        "Pelage Targe",
        "Studded Targe",
        "Crescent Targe",
        "Chiseled Targe",
        "Feathered Targe",
        "Stratified Targe",
        "Carved Targe",
        "Polished Targe",
        "Stone Targe",
        "Avian Targe",
        "Mammoth Targe",
        "Baroque Targe",
        "Soaring Targe",
        "Golden Targe",
    ];
    
    public static string[] EquipmentArmorEnergyShield =
    [
        // Helmet
        "Iron Crown",
        "Horned Crown",
        "Cultist Crown",
        "Martyr Crown",
        "Heavy Crown",
        "Spiritbone Crown",
        "Hallowed Crown",
        "Inquisitor Crown",
        "Druidic Crown",
        "Saintly Crown",
        "Divine Crown",
        "Cryptic Crown",
        
        // Chest
        "Pilgrim Vestments",
        "Pelt Mantle",
        "Mail Vestments",
        "Shaman Mantle",
        "Ironclad Vestments",
        "Sacrificial Mantle",
        "Cleric Vestments",
        "Tideseer Mantle",
        "Occultist Mantle",
        "Plated Vestments",
        "Heartcarver Mantle",
        "Wolfskin Mantle",
        "Conjurer Mantle",
        "Death Mantle",
        "Seastorm Mantle",
        
        // Gloves
        "Rope Cuffs",
        "Aged Cuffs",
        "Goldcast Cuffs",
        "Verisium Cuffs",
        "Ornate Cuffs",
        "Bound Cuffs",
        "Ancient Cuffs",
        "Gleaming Cuffs",
        "Adherent Cuffs",
        
        // Boots
        "Padded Leggings",
        "Secured Leggings",
        "Pelt Leggings",
        "Weaver Leggings",
        "Shamanistic Leggings",
        "Faithful Leggings",
        "Apostle Leggings",
        "Warlock Leggings",
        "Cryptic Leggings",
        
        // Shield
        "Blazon Crest Shield",
        "Sigil Crest Shield",
        "Emblem Crest Shield",
        "Jingling Crest Shield",
        "Sectarian Crest Shield",
        "Omen Crest Shield",
        "Wayward Crest Shield",
        "Seer Crest Shield",
        "Dekharan Crest Shield",
        "Quartered Crest Shield",
        "Glowering Crest Shield",
        "Intricate Crest Shield",
        "Sekheman Crest Shield",
        "Vaal Crest Shield",
        "Blacksteel Crest Shield",
    ];
    
    public static string[] EquipmentEvasionEnergyShield =
    [
        // Helmet
        "Hewn Mask",
        "Face Mask",
        "Hooded Mask",
        "Veiled Mask",
        "Tribal Mask",
        "Solid Mask",
        "Pariah Mask",
        "Avian Mask",
        "Brigand Mask",
        "Faridun Mask",
        "Soaring Mask",
        "Grinning Mask",
        
        // Chest
        "Hermit Garb",
        "Waxed Jacket",
        "Marabout Garb",
        "Wayfarer Jacket",
        "Anchorite Garb",
        "Scalper's Jacket",
        "Ascetic Garb",
        "Scoundrel Jacket",
        "Itinerant Jacket",
        "Hatungo Garb",
        "Hawker's Jacket",
        "Sleek Jacket",
        "Rambler Jacket",
        "Falconer's Jacket",
        "Austere Garb",
        
        // Gloves
        "Gauze Wraps",
        "Linen Wraps",
        "Spiral Wraps",
        "Buckled Wraps",
        "Adorned Wraps",
        "War Wraps",
        "Elegant Wraps",
        "Vaal Wraps",
        "Secured Wraps",
        
        // Boots
        "Frayed Shoes",
        "Threaded Shoes",
        "Hunting Shoes",
        "Steelpoint Shoes",
        "Treerunner Shoes",
        "Wanderer Shoes",
        "Charmed Shoes",
        "Quickslip Shoes",
        "Daggerfoot Shoes",
        
        // Shield
    ];
}
